#!/usr/bin/env bash
# Pulsar Spatial — cron wrapper for self-hosted deployment
#
# Usage in crontab:
#   30 8 * * 1-5 /path/to/Spatial-Intelligence-Handbook/scripts/pulsar/cron_runner.sh
#
# Required env (set in crontab or in a sourced file) — at least one LLM key:
#   DEEPSEEK_API_KEY   — DeepSeek deepseek-flash (primary)
#   DASHSCOPE_API_KEY  — Aliyun qwen (fallback)
#
# Optional env:
#   PULSAR_LOG_DIR     — log directory (default: /tmp)
#   PULSAR_NO_PUSH=1   — run pipeline, commit locally, but skip git push
#   PULSAR_NO_COMMIT=1 — run pipeline only, no git ops at all
#
# Safety:
#   - flock prevents concurrent runs (lock file in /tmp)
#   - git add scoped to reports/spatial-daily/ only (won't touch unrelated WIP)
#   - skip commit if no new content (e.g. weekend, zero qualifying papers)
#   - pull --rebase before push to minimize conflicts with other agents

set -euo pipefail

# --- Paths -----------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_DIR="${PULSAR_LOG_DIR:-/tmp}"
LOCK_FILE="${LOG_DIR}/pulsar-spatial.lock"
LOG_FILE="${LOG_DIR}/pulsar-spatial-$(date +%F).log"

# --- Lock (prevent concurrent runs) ---------------------------------
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
  echo "[$(date -Iseconds)] Another instance running, exit." >&2
  exit 0
fi

# --- Log rotation (auto-trim 30 day) --------------------------------
find "$LOG_DIR" -name "pulsar-spatial-*.log" -mtime +30 -delete 2>/dev/null || true

# --- Tee output to log + stderr -------------------------------------
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "════════════════════════════════════════════════════════════"
echo "[$(date -Iseconds)] Pulsar Spatial cron start"
echo "  REPO_ROOT=$REPO_ROOT"
echo "  LOG_FILE=$LOG_FILE"
echo "════════════════════════════════════════════════════════════"

# --- Sanity ----------------------------------------------------------
# Either key alone is enough; scripts/pulsar/_llm.py picks DeepSeek first and
# degrades to qwen. Neither set = guaranteed placeholder output, so stop here.
if [ -z "${DEEPSEEK_API_KEY:-}" ] && [ -z "${DASHSCOPE_API_KEY:-}" ]; then
  echo "ERROR: neither DEEPSEEK_API_KEY nor DASHSCOPE_API_KEY is set" >&2
  exit 1
fi

cd "$REPO_ROOT"

# --- 1. Run pipeline ------------------------------------------------
echo ""
echo "--- Stage 1: Run Pulsar pipeline ---"
if ! python3 scripts/pulsar/run_daily.py; then
  echo "ERROR: pipeline failed, abort." >&2
  exit 2
fi

# --- 1b. Curated non-arxiv signal (supplementary — never abort the run) ---
echo ""
echo "--- Stage 1b: Curated non-arxiv signal ---"
python3 scripts/pulsar/collect_curated.py || echo "WARN: curated signal failed (non-fatal), continuing." >&2

# --- 2. Sync README + audit -----------------------------------------
echo ""
echo "--- Stage 2: Sync README + audit ---"
python3 scripts/sync_readme_from_overview.py
if ! python3 scripts/handbook_audit.py; then
  echo "ERROR: audit FAIL, abort commit." >&2
  exit 3
fi

# --- 3. Commit + push (unless flagged off) --------------------------
if [ "${PULSAR_NO_COMMIT:-}" = "1" ]; then
  echo ""
  echo "PULSAR_NO_COMMIT=1, skip git ops. Done."
  exit 0
fi

echo ""
echo "--- Stage 3: git commit + push ---"

# Scope add to spatial-daily + curated-signal only (safe — won't touch unrelated WIP)
git add reports/spatial-daily/ reports/curated-signal/

# Skip if no new files
if git diff --staged --quiet; then
  echo "No new spatial-daily content — skip commit."
  exit 0
fi

# Persist the dedup caches (see the same block in pulsar-spatial-daily.yml).
# This self-hosted path has a persistent disk so the caches survive locally
# anyway, but they must still travel to the repo: the GitHub Actions runner is
# stateless and reads its cache from the checkout.
# Staged after the no-change check so a quiet day stays a no-commit day.
git add scripts/pulsar/state/seen_arxiv_ids.json scripts/pulsar/state/curated_seen.json

# Pull latest before commit (avoid concurrent agent conflicts)
git pull --rebase origin main || {
  echo "ERROR: rebase failed, manual intervention needed." >&2
  exit 4
}

# Commit
DATE=$(date +%F)
git -c user.name="Pulsar Bot" \
    -c user.email="noreply@anthropic.com" \
    commit -m "auto(pulsar): spatial daily ${DATE}

Generated by cron_runner.sh on $(hostname)
Pipeline: collect.py → rate.py (deepseek-flash, qwen fallback) → post.py"

# Push (unless flagged off)
if [ "${PULSAR_NO_PUSH:-}" = "1" ]; then
  echo "PULSAR_NO_PUSH=1, commit done but skip push."
  exit 0
fi

# Retry push once on conflict
if ! git push origin main; then
  echo "Push conflict, retrying after rebase..."
  git pull --rebase origin main
  git push origin main
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo "[$(date -Iseconds)] Pulsar Spatial cron done ✅"
echo "════════════════════════════════════════════════════════════"
